#!/usr/bin/env bash
# Do - The Simplest Build Tool on Earth.
# Documentation and examples see https://github.com/8gears/do
#
SCRIPTNAME=`basename "$0"`
BASEDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd ${BASEDIR}
source lib/util.sh
_load_env

install() {
    _need_root

    _apt-get-update
    _apt-get-install apt-listchanges gettext-base unattended-upgrades

    # Install lade
    #curl -fsSL https://raw.githubusercontent.com/zifeo/lade/main/installer.sh | bash
    #lade upgrade

    cp bin/envfile-sub /usr/local/bin/envfile-sub
}

uninstall() {
    _need_root

}

"$@" # <- execute the task
[ "$#" -gt 0 ] || printf "Usage:\n\t./${SCRIPTNAME} %s\n" "($(compgen -A function | grep '^[^_]' | paste -sd '|' -))"

