#!/usr/bin/env bash
# Do - The Simplest Build Tool on Earth.
# Documentation and examples see https://github.com/8gears/do
#
SCRIPTNAME=`basename "$0"`
BASEDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd ${BASEDIR}
source lib/util.sh
_load_env

install() {
    [ "$(id -u)" -eq 0 ] || { echo "This script must be run as root" >&2; exit 1; }

    cp $BASEDIR/dokuwiki.service /etc/systemd/system/dokuwiki.service
    systemctl daemon-reload
    systemctl enable --now dokuwiki
}

install-caddy() {
    [ "$(id -u)" -eq 0 ] || { echo "This script must be run as root" >&2; exit 1; }

    _apt-get-update
    _apt-get-install caddy gettext-base

    # Pull in our .env values if they exist
    _check_exists "FQDN"
    _check_exists "DESTIP"

    pushd /etc/caddy > /dev/null
    mkdir -p available enabled
    cat ${BASEDIR}/dokuwiki.caddyfile | envsubst > available/dokuwiki.caddyfile

    cd enabled
    ln -sf ../available/dokuwiki.caddyfile dokuwiki.caddyfile

    systemctl reload caddy

    popd > /dev/null
}

uninstall() {
    [ "$(id -u)" -eq 0 ] || { echo "This script must be run as root" >&2; exit 1; }

    # Remove systemd scripts
    pushd /etc/systemd/system > /dev/null
    rm -f tinc.service tinc\@.service
    popd > /dev/null

    echo Removed systemd integration.  Not removing data or docker containers.
}

"$@" # <- execute the task
[ "$#" -gt 0 ] || printf "Usage:\n\t./${SCRIPTNAME} %s\n" "($(compgen -A function | grep '^[^_]' | paste -sd '|' -))"

