---
all:
  children:
    internal:
      hosts:
        newtown:
          ansible_host: newtownenergy.com
          ansible_user: root
        bromine.newtown:
          ansible_host: bromine-newtown
          ansible_user: root

    # soltage:
    #   hosts:
    #     fiftyfive_drive:
    #       ansible_host: 8.8.8.8
    #       ansible_user: root
base:
  children:
    internal:

dokuwiki:
  hosts:
    bromine.newtown
openproject:
  hosts:
    bromine.newtown
openproject_proxy:
  hosts:
    newtown
msmtp:
  hosts:
    newtown
msmtp_proxy:
  hosts:
    bromine.newtown
neems_staging:
  hosts:
    bromine.newtown
neems_staging_proxy:
  hosts:
    newtown
seafile:
  hosts:
    bromine.newtown
seafile_proxy:
  hosts:
    newtown

caddy:
  hosts:
    newtown

vaultwarden:
  hosts:
    bromine.newtown:
