
all:
  children:
      internal:
          hosts:
            newtown:
              ansible_host: 143.198.120.154
              ansible_user: root
            bromine.newtown:
              ansible_host: 10.1.0.35
              ansible_user: root

        # soltage:
        #   hosts:
        #     fiftyfive_drive:
        #       ansible_host: 8.8.8.8
        #       ansible_user: root

dokuwiki:
  hosts:
    bromine.newtown
seafile:
  hosts:
    bromine.newtown
non_client:
  # hosts that aren't client sites
  hosts:
    bromine.newtown:
    newtown:
router:
  # Caddy front end and vpn router
  hosts:
    newtown

vaultwarden:
  hosts:
    bromine.newtown:
