---
all:
  children:
    internal:
      hosts:
        newtown:
          ansible_host: newtownenergy.com
          ansible_user: root
          perses_port: 8079
          perses_domains:
            - perses.newtown.energy
            - perses.newtownenergy.com
          perses_encryption_key_cmd: npass kv encryption-key box/newtown.energy/perses
          perses_admin_password_cmd: npass box/newtown.energy/perses | head -n 1
          victoria_metrics_username_cmd: npass kv username box/newtown.energy/victoria-metrics
          victoria_metrics_password_cmd: npass box/newtown.energy/victoria-metrics | head -n 1
          victoria_metrics_retention: 3d
          victoria_metrics_url: http://newtownenergy.com:8428/api/v1/write
          msmtpq_password_cmd: npass do-not-reply@newtownenergy.com | head -n 1
          msmtpq_from:
            - do-not-reply@newtownenergy.com
            - bot@newtownenergy.com
            - james@newtownenergy.com
        bromine.newtown:
          ansible_host: bromine.newtown
          ansible_user: root
          victoria_metrics_url: http://newtownenergy.com:8428/api/v1/write
          victoria_metrics_username_cmd: npass kv username box/newtown.energy/victoria-metrics
          victoria_metrics_password_cmd: npass box/newtown.energy/victoria-metrics | head -n 1

    # soltage:
    #   hosts:
    #     fiftyfive_drive:
    #       ansible_host: 8.8.8.8
    #       ansible_user: root
    
base:
  children:
    internal:

newtown-sendmail:
  hosts:
    newtown

monitor:
  hosts:
    newtown

monitored:
  hosts:
    newtown:
    bromine.newtown:

dokuwiki:
  hosts:
    bromine.newtown
openproject:
  hosts:
    bromine.newtown
openproject_proxy:
  hosts:
    newtown
msmtp:
  hosts:
    newtown
msmtp_proxy:
  hosts:
    bromine.newtown
neems_staging:
  hosts:
    bromine.newtown
neems_staging_proxy:
  hosts:
    newtown
seafile:
  hosts:
    bromine.newtown
seafile_proxy:
  hosts:
    newtown

caddy:
  hosts:
    newtown

vaultwarden:
  hosts:
    bromine.newtown:
