# This playbook pushes material to our invnetory-listed remotes.

# You might run it like this:
#
#     cd /opt/APPNAME
#     ap ../ansible/push

# Note that we don't specify which dosh to run except to say "run the
# one in the current directory".  That is intentional.  It is meant to
# be run from the dir containing the app we want to push.
#

# For one target remote host, you can just do `./dosh push FQDN`.  You
# only need this if you want to run multiple times from multiple
# targets, with those targets defined in our inventory.

---
- name: Push to remote app server
  hosts: '{{ appname }}'
  gather_facts: false
  vars:
    newtown_dir: "{{ lookup('ansible.builtin.env', 'NEWTOWN_DIR') }}"
    appname: "{{ lookup('ansible.builtin.env', 'PWD') | basename }}"
  tasks:

    # Note that this will exclude file globs listed one-to-a-line and
    # prefixed with "- " in .rsync-filter
    - name: Rsync . with remote, but not caddy
      ansible.posix.synchronize:
        src: "{{newtown_dir}}/src/deploy/{{appname}}"
        dest: /opt
        copy_links: true
        rsync_opts:
          - "--exclude=ansible"
          - "--exclude=caddyfile"
          - "--exclude=.git"
          - "--exclude=.gitignore"
          - "--exclude=.gitmodules"
          - "--exclude=.gitattributes"
          - "--exclude=*.swp"
          - "--exclude=.DS_Store"

- name: Push to remote proxy server
  hosts: '{{ appname+"_proxy" }}'
  gather_facts: false
  vars:
    newtown_dir: "{{ lookup('ansible.builtin.env', 'NEWTOWN_DIR') }}"
    appname: "{{ lookup('ansible.builtin.env', 'PWD') | basename }}"
  tasks:

    # Note that this will exclude file globs listed one-to-a-line and
    # prefixed with "- " in .rsync-filter
    - name: Rsync to reverse proxy frontend
      ansible.posix.synchronize:
        src: "{{newtown_dir}}/src/deploy/{{appname}}"
        dest: /opt
        copy_links: true
        rsync_opts:
          - "--exclude=.service"
          - "--exclude=*.yml"
          - "--exclude=ansible"
          - "--exclude=.git"
          - "--exclude=.gitignore"
          - "--exclude=.gitmodules"
          - "--exclude=.gitattributes"
          - "--exclude=*.swp"
          - "--exclude=.DS_Store"
