---
- name: Deploy Flask Docker app with env vars from Bitwarden, no .env file
  hosts: bromine.newtown
  gather_facts: false
  vars:
    flask_app_dir: /opt/demo
    vaultid: "{{ lookup('env', 'VAULTID') }}"
  tasks:
    - name: Pull and run Flask Docker app with environment variables
      ansible.builtin.shell: |
        docker compose down || true
        docker compose pull || true
        docker compose up -d --build
      args:
        chdir: "{{ flask_app_dir }}"
      environment:
        SMTP_USER: "{{ lookup('community.general.bitwarden', vaultid, search='id', field='SMTP_USER') | first }}"
        SMTP_HOST: "{{ lookup('community.general.bitwarden', vaultid, search='id', field='SMTP_HOST') | first }}"
        SMTP_FROM_ADDRESS: "{{ lookup('community.general.bitwarden', vaultid, search='id', field='SMTP_FROM_ADDRESS') | first }}"
