#!/usr/bin/env bash
# Do - The Simplest Build Tool on Earth.
# Documentation and examples see https://github.com/8gears/do
#
SCRIPTNAME=`basename "$0"`
BASEDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
APPNAME=$(basename "${BASEDIR}")
cd ${BASEDIR}
source lib/util.sh

export VAULTID="cda8f639-96d1-463d-ae80-3923f0e05b9a"

install() {
    echo No install step needed for this app.
}

_get_fields() {
    # Corrected Perl one-liner (added missing semicolon)
    fields=$(perl -MJSON -e '
	my $item = decode_json(`bw get item "$ENV{VAULTID}"`);
	my %fields = map { $_->{name} => $_->{value} } @{$item->{fields}};
	print encode_json(\%fields);
    ')
}

_export_fields() {
    while read -r line; do
        eval "$line"
    done < <(
        perl -MJSON -e '
            my $item = decode_json(`bw get item "$ENV{VAULTID}"`);
            foreach my $field (@{$item->{fields}}) {
                my $name = $field->{name};
                my $value = $field->{value};
                $value =~ s/"/\\"/g;  # Escape any double quotes
                print "export $name=\"$value\"\n";
            }
        '
    )
}

fields() {
    ## Get our environment variables from Bitwarden
    _get_fields
    echo "$fields"
}


run() {
    _export_fields
    ansible-playbook deploy.yml -i ../ansible/inventory.yaml
}

"$@" # <- execute the task
[ "$#" -gt 0 ] || printf "Usage:\n\t./${SCRIPTNAME} %s\n" "($(compgen -A function | grep '^[^_]' | paste -sd '|' -))"

